# -*- coding: utf-8 -*-
"""Job Recommendation System using ANN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dR-IKm299jwxZmWX7k6EWZvRlufETzif
"""

import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# Features:
# [coding, math, ml, web, experience, degree]
X = np.array([
    [8, 6, 2, 3, 2, 1],  # Software Dev
    [9, 9, 8, 2, 3, 1],  # Data Scientist
    [6, 3, 1, 9, 1, 1],  # Web Dev
    [8, 8, 9, 3, 2, 1],  # AI/ML Engineer
    [7, 6, 3, 8, 2, 1],
    [9, 8, 7, 2, 4, 1],
    [5, 4, 1, 7, 1, 0],
    [8, 9, 8, 3, 3, 1]
])

# Job labels
# 0: Software Dev, 1: Data Scientist, 2: Web Dev, 3: AI/ML Engineer
y = np.array([0, 1, 2, 3, 2, 1, 2, 3])
y = to_categorical(y)

scaler = StandardScaler()
X = scaler.fit_transform(X)

model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(6,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X, y, epochs=200, verbose=0)
print("Model training completed.")

jobs = ["Software Developer", "Data Scientist",
        "Web Developer", "AI/ML Engineer"]

print("\n--- Job Recommendation System ---")
coding = int(input("Enter Coding Skill (0-10): "))
math = int(input("Enter Math Skill (0-10): "))
ml = int(input("Enter ML Knowledge (0-10): "))
web = int(input("Enter Web Knowledge (0-10): "))
exp = int(input("Enter Experience (years): "))
degree = int(input("Degree (1 = CS/IT, 0 = Non-CS): "))

user_data = np.array([[coding, math, ml, web, exp, degree]])
user_data = scaler.transform(user_data)

prediction = model.predict(user_data)
job_index = np.argmax(prediction)

print("\n✅ Recommended Job Role:", jobs[job_index])



!pip install streamlit

import numpy as np
import streamlit as st
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

st.title("Job Recommendation System using ANN")

coding = st.slider("Coding Skill", 0, 10, 5)
math = st.slider("Math Skill", 0, 10, 5)
ml = st.slider("ML Knowledge", 0, 10, 5)
web = st.slider("Web Knowledge", 0, 10, 5)
exp = st.slider("Experience (years)", 0, 10, 1)
degree = st.selectbox("Degree", ["Non-CS", "CS/IT"])

degree = 1 if degree == "CS/IT" else 0

if st.button("Recommend Job"):
    user_data = np.array([[coding, math, ml, web, exp, degree]])
    user_data = scaler.transform(user_data)

    prediction = model.predict(user_data)
    job_index = np.argmax(prediction)

    jobs = ["Software Developer", "Data Scientist",
            "Web Developer", "AI/ML Engineer"]

    st.success(f"Recommended Job: {jobs[job_index]}")