# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usv3Xr10bqc5j41TWPMv-6__W7lOj3qK
"""

streamlit
numpy
scikit-learn
tensorflow