# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usv3Xr10bqc5j41TWPMv-6__W7lOj3qK
"""

streamlit==1.32.2
numpy==1.26.4
scikit-learn==1.4.2
tensorflow==2.15.0
